version: '3'
services:
  samba:
    build: .
    container_name: samba-server
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /home/frenzy/shared:/srv/samba/shared
    restart: always
